TargDeMuzica/Models/Product.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.ObjectModelRemoting;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TargDeMuzica.Models
{
    public class Product
    {
        [Key]
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        
        public float ProductPrice { get; set; }
        public int ProductStock { get; set; }
        public string? ProductImageLocation {  get; set; }
        public float? ProductScore { get; set; }

        public string? ProductGenresTemp { get; set; }
        public List<string>? ProductGenres { get; set; }


        //foreign key MusicSuport == categorie
        public int? MusicSuportID { get; set; }
        public virtual MusicSuport? MusicSuport { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem>? MusicSup { get; set; }
        //foreign key Artist
        public int? ArtistID { get; set; }
        public virtual Artist? Artist { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem>? ArtistList { get; set; }
        //many to many products - carts
        public virtual ICollection<Cart>? Carts { get; set; }
        //vector review
        public ICollection<Review>? Reviews { get; set; }
        public string? UserId { get; set; }
        public virtual ApplicationUser? User { get; set; }
    }
}

TargDeMuzica/Controllers/CartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TargDeMuzica.Data;
using TargDeMuzica.Models;

namespace TargDeMuzica.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext db;

        public CartsController(ApplicationDbContext context)
        {
            db = context;
        }
        [Authorize(Roles = "UserI, UserN, Administrator, Colaborator")]
        public IActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            var carts = from cart in db.Carts
                          orderby cart.TotalPrice
                          select cart;

            ViewBag.Carts = carts;
            return View();
        }
        public ActionResult Show(int id)
        {
            Cart cart = db.Carts.Find(id);
            return View(cart);
        }


        public ActionResult Edit(int id)
        {
           Cart cart = db.Carts.Find(id);
            return View(cart);
        }

        [HttpPost]
        public ActionResult Edit(int id, Cart requestCart)
        {
            Cart cart = db.Carts.Find(id);

            try
            {

                cart.TotalPrice = requestCart.TotalPrice;
                db.SaveChanges();
                TempData["message"] = "Cartul a fost editat cu succes!";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(requestCart);
            }
        }

    
    }
}

TargDeMuzica/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Collections.Specialized;
using System.Composition;
using System.Drawing.Printing;
using TargDeMuzica.Data;
using TargDeMuzica.Models;
using static TargDeMuzica.Models.IncomingRequest;

namespace TargDeMuzica.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _env;

        public ProductsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
                                    RoleManager<IdentityRole> roleManager, IWebHostEnvironment env)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }

        public IActionResult Index(string search, string sortBy = "name", string sortOrder = "asc")
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            var pendingProductIds = db.IncomingRequests
                .Where(r => r.Status == IncomingRequest.RequestStatus.Rejected || r.Status == IncomingRequest.RequestStatus.Pending)
                .Select(r => r.ProposedProduct.ProductID);

            
            var productsQuery = db.Products
                                    .Include(p => p.User)  
                                    .Where(p => !pendingProductIds.Contains(p.ProductID));

            
            if (!string.IsNullOrWhiteSpace(search))
            {
                search = search.Trim();
                productsQuery = productsQuery.Where(p => p.ProductName.Contains(search));
            }

            
            productsQuery = sortBy.ToLower() switch
            {
                "price" => sortOrder.ToLower() == "asc"
                    ? productsQuery.OrderBy(p => p.ProductPrice)
                    : productsQuery.OrderByDescending(p => p.ProductPrice),
                "rating" => sortOrder.ToLower() == "asc"
                    ? productsQuery.OrderBy(p => p.ProductScore)
                    : productsQuery.OrderByDescending(p => p.ProductScore),
                _ => sortOrder.ToLower() == "asc"  
                    ? productsQuery.OrderBy(p => p.ProductName)
                    : productsQuery.OrderByDescending(p => p.ProductName)
            };

            var products = productsQuery.ToList();

            
            ViewBag.Products = products;
            ViewBag.SearchString = search;
            ViewBag.CurrentSort = sortBy;
            ViewBag.CurrentSortOrder = sortOrder;

            if (!string.IsNullOrEmpty(search))
            {
                ViewBag.PaginationBaseUrl = $"/Products/Index/?search={search}&sortBy={sortBy}&sortOrder={sortOrder}&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = $"/Products/Index/?sortBy={sortBy}&sortOrder={sortOrder}&page";
            }

            return View();
        }




        public ActionResult Show(int id)
        {
            Product product = db.Products
                .Include(p => p.Reviews)
                .Include(p => p.MusicSuport)
                .Include(p => p.Artist)
                .FirstOrDefault(p => p.ProductID == id);

            if (product == null)
            {
                return NotFound();
            }

            if (product.Reviews != null && product.Reviews.Any())
            {
                product.ProductScore = (float)product.Reviews.Average(r => r.StarRating);
                db.SaveChanges();
            }

            return View(product);
        }



        [NonAction]
        public IEnumerable<SelectListItem> GetAllMusicSup()
        {
           
            var selectList = new List<SelectListItem>();
            var sup = from su in db.MusicSuports
                             select su;

            foreach (var su in sup)
            {
                selectList.Add(new SelectListItem
                {
                    Value = su.MusicSuportID.ToString(),
                    Text = su.MusicSuportName
                });
            }

            return selectList;
        }
        [NonAction]
        public IEnumerable<SelectListItem> GetAllArtists()
        {
            var selectList = new List<SelectListItem>();
            var artist = from art in db.Artists
                      select art;

            foreach (var art in artist)
            {
                selectList.Add(new SelectListItem
                {
                    Value = art.ArtistID.ToString(),
                    Text = art.ArtistName
                });
            }

            return selectList;
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult New()
        {
            Product produs = new Product();
            produs.MusicSup = GetAllMusicSup();
            produs.ArtistList = GetAllArtists();
            return View(produs);
        }
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> New(Product prod, IFormFile Image)
        {
            try
            {
                if (Image != null && Image.Length > 0)
                {
                    var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif", ".mp4", ".mov" };
                    var fileExtension = Path.GetExtension(Image.FileName).ToLower();

                    if (!allowedExtensions.Contains(fileExtension))
                    {
                        ModelState.AddModelError("ArticleImage", "Fișierul trebuie să fie o imagine(jpg, jpeg, png, gif) sau un video(mp4, mov).");
                        prod.MusicSup = GetAllMusicSup();
                        prod.ArtistList = GetAllArtists();
                        return View(prod);
                    }

                    var imagesPath = Path.Combine(_env.WebRootPath, "images");
                    var storagePath = Path.Combine(imagesPath, Image.FileName);
                    var databaseFileName = "/images/" + Image.FileName;

                    using (var fileStream = new FileStream(storagePath, FileMode.Create))
                    {
                        await Image.CopyToAsync(fileStream);
                    }

                    prod.ProductImageLocation = databaseFileName;
                }
                else
                {
                    ModelState.AddModelError("Image", "An image file is required");
                    prod.MusicSup = GetAllMusicSup();
                    prod.ArtistList = GetAllArtists();
                    return View(prod);
                }

                var currentUser = await _userManager.GetUserAsync(User);
                prod.User = currentUser;

                prod.ProductGenres = prod.ProductGenresTemp.Split(' ').ToList();
                db.Products.Add(prod);
                db.SaveChanges();
                TempData["message"] = "Produsul a fost adaugat!";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                prod.MusicSup = GetAllMusicSup();
                prod.ArtistList = GetAllArtists();
                return View(prod);
            }
        }
        [Authorize(Roles = "Colaborator,Administrator")]
        public ActionResult Edit(int id)
        {
            Product prod = db.Products.Find(id);
            prod.MusicSup = GetAllMusicSup();
            prod.ArtistList = GetAllArtists();
            return View(prod);
        }

        [Authorize(Roles = "Colaborator,Administrator")]
        [HttpPost]
        public ActionResult Edit(int id, Product requestProd)
        {
            Product prod = db.Products.Find(id);

            try
            {

                prod.ProductName = requestProd.ProductName;
                prod.ProductDescription = requestProd.ProductDescription;
                prod.MusicSuportID = requestProd.MusicSuportID;
                prod.ProductPrice = requestProd.ProductPrice;
                prod.ProductStock = requestProd.ProductStock;
                prod.ProductImageLocation = requestProd.ProductImageLocation;
                prod.ProductScore = requestProd.ProductScore;
                prod.ProductGenres = requestProd.ProductGenres;
                prod.ArtistID = requestProd.ArtistID;
                prod.Carts = requestProd.Carts;
                prod.Reviews = requestProd.Reviews;
                prod.User = requestProd.User;

                //de trimis in incomingrequests si sa fie de acolo bagat in
                //baza de date ce am facut mai sus

                db.SaveChanges();
                TempData["message"] = "Produsul a fost editat cu succes";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                prod.MusicSup = GetAllMusicSup();
                prod.ArtistList = GetAllArtists();
                return View(requestProd);
            }
        }

        [Authorize(Roles = "Colaborator,Administrator")]
        public ActionResult Delete(int id)
        {
            try
            {
                Product product = db.Products
                    .Include(p => p.Reviews)  
                    .FirstOrDefault(p => p.ProductID == id);

                if (product == null)
                {
                    return NotFound();
                }

                if (product.Reviews != null && product.Reviews.Any())
                {
                    db.Reviews.RemoveRange(product.Reviews);
                }

TargDeMuzica/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TargDeMuzica.Data;
using TargDeMuzica.Models;

namespace TargDeMuzica.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public ReviewsController(
            ApplicationDbContext _db,
            UserManager<ApplicationUser> _userManager,
            RoleManager<IdentityRole> _roleManager)
        {
            db = _db;
            userManager = _userManager;
            roleManager = _roleManager;
        }

        public IActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            var reviews = from review in db.Reviews
                          orderby review.ReviewContent
                          select review;

            ViewBag.Reviews = reviews;
            return View();
        }
        public ActionResult Show(int id)
        {
            Review review = db.Reviews.Find(id);
            return View(review);
        }

        public ActionResult New()
        {
            return View();
        }
        [Authorize(Roles = "UserI, Colaborator, Administrator")]
        [HttpPost]
        public async Task<ActionResult> New(Review rev)
        {


            if(ModelState.IsValid)
            {
                rev.ReviewDate = DateTime.Now;
                rev.User = await userManager.GetUserAsync(User);
                db.Reviews.Add(rev);
                db.SaveChanges();
                TempData["message"] = "Review-ul a fost adaugat";

                


                return RedirectToAction("Show", "Products", new { id = rev.ProductId });

            }
            else
            {
                return RedirectToAction("Show", "Products", new { id = rev.ProductId });
            }
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            Review review = db.Reviews.Find(id);
            return View(review);
        }

        [Authorize(Roles ="Administrator")]
        [HttpPost]
        public ActionResult Edit(int id, Review requestReview)
        {
            Review review = db.Reviews.Find(id);

            try
            {

                review.ReviewContent = requestReview.ReviewContent;
                review.ReviewDate = requestReview.ReviewDate;
                review.StarRating = requestReview.StarRating;

                db.SaveChanges();
                TempData["message"] = "Comentariul a fost adugat cu succes!!";
                return RedirectToAction("Show", "Products", new { id = review.ProductId });
            }
            catch (Exception e)
            {
                return View(requestReview);
            }
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
           Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            TempData["message"] = "Review-ul a fost sters";
            return RedirectToAction("Show", "Products", new { id = review.ProductId });
        }
    }
}

TargDeMuzica/Views/Products/Edit.cshtml
@model TargDeMuzica.Models.Product

@{
    ViewData["Title"] = Model.ProductID == 0 ? "Create Product" : "Edit Product";
}

<h1>@ViewData["Title"]</h1>
<a class="btn alert-success" asp-action="Delete" asp-controller="Products" asp-route-id="@Model.ProductID">Stergere produs</a>
<div class="row">
    <div class="col-md-8">
        <form asp-action="@(Model.ProductID == 0 ? "Create" : "Edit")">
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <textarea asp-for="ProductDescription" class="form-control"></textarea>
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" type="number" step="0.01" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductStock" class="control-label"></label>
                <input asp-for="ProductStock" class="form-control" type="number" />
                <span asp-validation-for="ProductStock" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProductImageLocation" class="control-label"></label>
                <input asp-for="ProductImageLocation" class="form-control" />
                <span asp-validation-for="ProductImageLocation" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="ProductGenresTemp" class="control-label">Genres</label>
                <input asp-for="ProductGenresTemp" class="form-control" placeholder="Enter genres separated by commas" />
                <span asp-validation-for="ProductGenresTemp" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MusicSuportID" class="control-label">Music Support</label>
                <select asp-for="MusicSuportID" asp-items="Model.MusicSup" class="form-control"></select>
                <span asp-validation-for="MusicSuportID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ArtistID" class="control-label">Artist</label>
                <select asp-for="ArtistID" asp-items="Model.ArtistList" class="form-control"></select>
                <span asp-validation-for="ArtistID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TargDeMuzica/Views/Products/Show.cshtml
@model TargDeMuzica.Models.Product
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<TargDeMuzica.Models.ApplicationUser> UserManager
<style>

    .fixed-bottom-right {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 1000;
    }

    .btn-float {
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        padding: 12px 24px;
    }

    :root {
    }

    body {
        color: var(--text-color);
        background-color: #f8f8be;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .product-title {
        color: var(--accent-color);
        font-size: 2.5rem;
        margin: 2rem 0;
        text-align: center;
        font-weight: 600;
    }

    .product-container {
        background-color: var(--secondary-color);
        border-radius: 15px;
        padding: 2rem;
        margin: 2rem 0;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .product-image {
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .product-details dt {
        color: var(--accent-color);
        font-weight: 600;
        padding: 0.5rem 0;
    }

    .product-details dd {
        margin-bottom: 1rem;
    }

    .btn-custom {
        background-color: var(--primary-color);
        color: black;
        padding: 0.75rem 1.5rem;
        border-radius: 25px;
        border: none;
        transition: all 0.3s ease;
    }

        .btn-custom:hover {
            background-color: #f9fae0;
            transform: translateY(-2px);
            color: black;
        }

    .btn-secondary {
        background-color: var(--accent-color);
    }

    .review-section {
        background-color: var(--light-gray);
        padding: 2rem;
        border-radius: 15px;
        margin-top: 3rem;
    }

    .review-form {
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
    }

    .review-card {
        border-radius: 10px;
        margin-bottom: 1.5rem;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
        transition: transform 0.2s ease;
    }

        .review-card:hover {
            transform: translateY(-3px);
        }

    .star-rating {
        color: #ffd700;
    }

    .empty-star {
        color: #d1d1d1;
    }
</style>

<h1 class="product-title">@Model.ProductName</h1>



<div class="product-container">
    <div class="row">
        <div class="col-md-6">
            <div class="product-image">
                @if (Model.ProductImageLocation.Contains(".mp4") || Model.ProductImageLocation.Contains(".mov"))
                {
                    <video width="100%" height="450" controls class="rounded">
                        <source src="@Model.ProductImageLocation" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                }
                else
                {
                    <img src="@Model.ProductImageLocation" alt="Product image" class="img-fluid rounded" style="width:100%; height: 450px; object-fit: cover" />
                }
            </div>
        </div>
        <div class="col-md-6">
            <dl class="row product-details">
                <dt class="col-sm-4">Description:</dt>
                <dd class="col-sm-8">@Model.ProductDescription</dd>

                <dt class="col-sm-4">Price:</dt>
                <dd class="col-sm-8 h4 text-primary">@Model.ProductPrice.ToString("C")</dd>

                <dt class="col-sm-4">Stock:</dt>
                <dd class="col-sm-8">@Model.ProductStock</dd>

                <dt class="col-sm-4">Score:</dt>
                <dd class="col-sm-8">@(Model.ProductScore.HasValue ? Model.ProductScore.Value.ToString("F1") : "Not Rated")</dd>

                <dt class="col-sm-4">Genres:</dt>
                <dd class="col-sm-8">@(Model.ProductGenres != null ? string.Join(", ", Model.ProductGenres) : "None")</dd>

                <dt class="col-sm-4">Music Support:</dt>
                <dd class="col-sm-8">
                    @(Model.MusicSuport?.MusicSuportName ?? "Unknown")
                </dd>

                <dt class="col-sm-4">Artist:</dt>
                <dd class="col-sm-8">@(Model.Artist != null ? Model.Artist.ArtistName : "Unknown")</dd>
            </dl>

            <div class="mt-4">
                <a asp-controller="Carts" asp-action="Index" class="btn btn-custom" style="background-color: #28a745; color: white;">Add to Cart</a>
            </div>

        </div>
    </div>
</div>


        </div>
    </div>
</div>

<div class="review-section">
    <h2 class="mb-4">Add a Review</h2>
    <div class="review-form">
        @if (SignInManager.IsSignedIn(User))
        {
            <form asp-controller="Reviews" asp-action="New" method="post">
                <input type="hidden" name="ProductId" value="@Model.ProductID" />
                <input type="hidden" name="ReturnUrl" value="@Context.Request.Path" />


                <div class="form-group mb-3">
                    @{
                        var user = await UserManager.GetUserAsync(User);
                        var userName = user?.UserName ?? "Anonymous";
                    }
                    <input type="hidden" id="ReviewerName" name="ReviewerName" value="@userName" />
                    <div class="text-muted">Posting review as: @userName</div>
                </div>

                <div class="form-group mb-3">
                    <label for="ReviewContent" class="form-label">Review Content</label>
                    <textarea class="form-control" id="ReviewContent" name="ReviewContent" rows="4"
                              placeholder="Share your thoughts about this product..."></textarea>
                </div>

                <div class="form-group mb-3">
                    <label for="StarRating" class="form-label">Rating</label>
                    <select class="form-control" id="StarRating" name="StarRating" required>
                        <option value="" disabled selected>Select a rating</option>
                        @for (int i = 1; i <= 5; i++)
                        {
                            <option value="@i">@i Star@(i > 1 ? "s" : "")</option>
                        }
                    </select>
                </div>

                <button type="submit" class="btn btn-custom">Submit Review</button>
            </form>
        }
        else
        {
            <div class="alert alert-warning">
                You must be signed in to leave a review.
            </div>
        }
    </div>

    <div class="mt-5">
        <h2 class="mb-4">Product Reviews</h2>
        @if (Model != null)
        {
            @if (Model.Reviews != null && Model.Reviews.Any())
            {
                foreach (var review in Model.Reviews.OrderByDescending(r => r.ReviewDate))
                {
                    <div class="review-card p-4">
                        <div class="d-flex justify-content-between align-items-start">
                            <div class="flex-grow-1">
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5 class="mb-1">@review.ReviewerName</h5>
                                    <div class="star-rating">
                                        @for (int i = 0; i < review.StarRating; i++)
                                        {
                                            <span>★</span>
                                        }
                                        @for (int i = review.StarRating; i < 5; i++)
                                        {
                                            <span class="empty-star">☆</span>
                                        }
                                    </div>
                                </div>
                                <div class="text-muted small mb-3">
                                    @review.ReviewDate.ToString("MMMM dd, yyyy")
                                </div>
                                <p class="mb-0">@review.ReviewContent</p>
                            </div>

                            @if (User.IsInRole("Administrator"))
                            {
                                <div class="ms-3">
                                    <div class="d-flex gap-2">
                                        <a class="btn btn-custom btn-sm"
                                           asp-controller="Reviews"
                                           asp-action="Edit"
                                           asp-route-id="@review.ReviewID">
                                            Edit
                                        </a>
                                        <a class="btn btn-custom btn-secondary btn-sm"
                                           asp-controller="Reviews"
                                           asp-action="Delete"
                                           asp-route-id="@review.ReviewID"
                                           onclick="return confirm('Are you sure you want to delete this review?');">
                                            Delete
                                        </a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="review-card p-4 text-center">
                    <p class="text-muted mb-0">No reviews yet. Be the first to review this product!</p>
                </div>
            }
        }
    </div>
</div>

<div class="fixed-bottom-right">
    <a asp-action="Index" class="btn btn-custom btn-secondary btn-float">Back to List</a>
</div>